# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js unit tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  MY_NAME: nnnnn

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} name is - ${{env.MY_NAME}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run test:prod
# add eslint and prettier test to the workflow
#     - name: Install dependencies
#       run: npm install
#     - name: Lint with ESLint
#       run: npm run lint
#     - name: Lint with Prettier
#       run: npm run format:check
